### ISSUE TITLE
[BUG] Short Description

### ISSUE THREAD

**Issue by Ahrimanius** [jurialmunkey/skin.arctic.fuse#208]
### Skin section

Home Widgets

### Current Behavior

Device: Nvidia Shield 2017/Samsung Galaxy Tab S8

Kodi Version: v 20.2 Nexus

Skin: Arctic Fuse v.0.3.23

Add-on: TMDB Helper v 5.2.4~nexus

Turned on my Devices today using stock Arctic Fuse and Homescreen Widgets refuse to load leaving the Catagory Blank (Home,Movie,TV Show)
Submenu Items in Home: New,In Progress etc are visible and work

Movie & TV Catagory only show Source 

Tried all available Layout Styles (Catagories, Compound, Composite,Combined, Classic) issue persists.

Spotlight is showing Movies & TV Shows plus Ratings

Add-ons are working fine (Artwork, Ratings, Playback etc)

Cleared all Cache

Tested with a complete new Kodi Install only having Arctic Fuse,TMDB Helper & one other Video addon ( all Add-ons Configured with Meta accounts/API etc.)

Same Issue on a fresh "bare bones" set up right out of the gate 

### Expected Behavior

For stock unmodified Arctic Fuse after Set up Wizard to Display Widgets.

### Steps To Reproduce

1.Fresh Kodi 20.2 Install 
2.Install Arctic Fuse plus Dependancy's
3.Run Skin Set up Wizard.

Homescreen does not Display Homescreen Widgets regardless of selected Layout.

### Screenshots and Additional Info

Log: https://paste.kodi.tv/labeneguva

https://i.imgur.com/zPZlSbU.jpg (Homescreen)

https://i.imgur.com/J2xknbD.jpg (Movies)

https://i.imgur.com/DE7G0ID.jpg (TV Shows)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is a skinshortcuts error. Because it is erroring, it wont build anything.

I've never seen this error before. From the traceback, I can see the error is in its playlists code when it tries to read the playlists in your library. My best guess is that you've got a corrupted smart playlist file which skinshortcuts cant read properly (unfortunately it doesn't give much logging in terms of what exactly).

You can usually find your playlists in `.kodi/userdata/playlists` or if you use profiles they might also be in `.kodi/userdata/profiles/profilename/playlists`

My recommendation would be to backup those folders and then delete all the playlists inside them, restart Kodi and see if you still get the error.

**Comment by Ahrimanius** [comment]
https://paste.kodi.tv/wazehuleya

I deleted the playlist XML files I found under userdata/playlists (don't use multiple profiles)

Restarted Kodi

Skin was working till I changed the Layout Style via Set-up Wizard

Arctic Fusion is being "selective" with what widgets it is displaying
All playlist XML files have been removed 
after checking the folder(s) in question remain empty
With no further playlist xmls created

https://i.imgur.com/SEpjIPM.jpg (composite)
https://i.imgur.com/jhhJNP4.jpg (composite)
https://i.imgur.com/faddaVE.jpg (composite)
https://i.imgur.com/duYKMQE.jpg (classic)
https://i.imgur.com/sMcH3MF.jpg (Combined)
https://i.imgur.com/98hWfI1.jpg (Combined)
https://i.imgur.com/xhkNUoj.jpg (Combined)

**Comment by Uka-Uka** [comment]
The last update did this to me also, on my Android TV. I'm willing to provide any logs if needed.

**Comment by Uka-Uka** [comment]
I kept rolling back through the releases. v0.3.23 was the one introduced that bug to the android devices.

**Comment by jurialmunkey** [comment]
This is addressed in v0.4 which will be released in next couple of days. Preview is available from omega testing branch:
https://github.com/jurialmunkey/skin.arctic.fuse/archive/refs/heads/omega_testing.zip
 
v0.4 no longer uses SkinShortcuts at all and new script from widget management is not compatible with its config files, so it wont inherit your old setup (but it also won't touch the files, so you can also roll back as needed).

There will be an import function to help migrate some of the configuration but it isn't quite ready yet, hence why I haven't added it to my Kodi repo yet -- but you can get early preview from the zip above.

**Comment by Uka-Uka** [comment]
@Ahrimanius Did the latest update fix the problem for you? I still have the same issue with the latest version.

**Comment by jurialmunkey** [comment]
@Uka-Uka What is the exact issue, because it is impossible to have skinshortcuts error in the v0.4 onwards as it is not used

**Comment by jurialmunkey** [comment]
If you are just saying that widgets are empty that's probably because you have no content in your library and the default widget set uses library content. 

You can change the widget set used in the widget configuration dialog by using the "prebuilt" button on the side and switching to the TMDb set.

https://imgur.com/a/py3Qt3G

**Comment by Ahrimanius** [comment]
> If you are just saying that widgets are empty that's probably because you have no content in your library and the default widget set uses library content.
> 
> You can change the widget set used in the widget configuration dialog by using the "prebuilt" button on the side and switching to the TMDb set.
> 
> https://imgur.com/a/py3Qt3G

This Worked 

Thanks

But I have yet to figure out how to display pre configurerd widgets for Example "Popular" or Top Rated

Because atleast for me the Home Menu Item only Displays Trending,Best Movies Last Decade, Random Movies Genere

Using the Catagories View from Set up Wizard.

Unless of course this is intentional with Version 0.4

**Comment by jurialmunkey** [comment]
You go to the edit widgets page, highlight the home link and choose edit categories, then from there you edit each category and choose which widgets you'd like each to have.

**Comment by Uka-Uka** [comment]
> If you are just saying that widgets are empty that's probably because you have no content in your library and the default widget set uses library content.
> 
> You can change the widget set used in the widget configuration dialog by using the "prebuilt" button on the side and switching to the TMDb set.
> 
> https://imgur.com/a/py3Qt3G

Apologies for the long silence! The level and quality of assistance you provide to users is unmatched, and I truly appreciate it.

I have made the Home Hub content-rich again by following your instructions. In my opinion, the setup wizard could improve user experience slightly by allowing users to choose between utilizing the Library and TMDB pre-built lists.

If you don't mind, I am experiencing some minor issues that I would like to discuss with you. I'm not sure if what I'm facing is expected behavior or not...

1) The Spotlight feature is no longer functional. I have tried both layouts featured in it, but they haven't been helpful.
https://i.imgur.com/KmM7AsD.png

2) Are submenus in the home hub such as Popular, Top Rated, and Upcoming supposed to display different widgets when focused on? Currently, they do not.

3) After selecting TMDB prebuilt lists as you demonstrated, both Movies and TV Shows hubs behave differently compared to version 0.3.x of the skin. They now refer to a corresponding TMDBhelper page which is fine; however, I really miss the old prebuilt lists for these two hubs. They were intuitive to use and showcased the beauty of the skin with ready-made content.

**Comment by Uka-Uka** [comment]
@jurialmunkey Sorry if I'm pestering you, may you check my last reply?

**Comment by jurialmunkey** [comment]
@Uka-Uka you can configure the menus however you like in the widget configuration screen. All of these things can be setup there according to your needs.

Adding trakt lists by default is problematic for users who do not use trakt, so I no longer do that by default so that they aren't constantly asked to login to trakt. You can still add these lists and setup the menu how you like via customisation dialog.
